import React, { useState } from "react";
import { fetchFromAPI } from "./helpers";
import { CardElement, useStripe, useElements } from "@stripe/react-stripe-js";

export default function Payments() {
  const stripe = useStripe();
  const elements = useElements();

  const [amount, setAmount] = useState(0);
  const [paymentIntent, setPaymentIntent] = useState();

  // create a payment intent on the server
  // We do this before we collect the user's credit card information
  const createPaymentIntent = async (event) => {
    // Clamp amount to Stripe's min/max - amount should be > 50 and < 9999999 (cents)
    const validAmount = Math.min(Math.max(amount, 50), 9999999);
    setAmount(validAmount);

    // API request
    const intent = await fetchFromAPI("payments", {
      body: { amount: validAmount },
    });

    // the paymentIntent generated by stripe includes the client_secret we need later
    setPaymentIntent(intent);
  };

  // handle user credit card input
  const handleSubmit = async (event) => {
    event.preventDefault();
    const cardElement = elements.getElement(CardElement);

    // Confirm the card payment
    const { paymentIntent: updatedPaymentIntent, error } =
      await stripe.confirmCardPayment(paymentIntent.client_secret, {
        payment_method: { card: cardElement },
      });

    if (error) {
      console.log(error);
      error.payment_intent && setPaymentIntent(error.payment_intent);
    } else {
      setPaymentIntent(updatedPaymentIntent);
    }
  };

  return (
    <>
      <div>
        <input
          type="number"
          value={amount}
          disabled={paymentIntent}
          onChange={(e) => setAmount(e.target.value)}
        />
        <button
          disabled={amount <= 0}
          onClick={createPaymentIntent}
          hidden={paymentIntent}
        >
          Ready to Pay {(amount / 100).toFixed(2)}
        </button>
      </div>

      <form onSubmit={handleSubmit}>
        {/* can customize CardElement with custom CSS */}
        <CardElement />
        <button type="submit">Pay</button>
      </form>
    </>
  );
}
